---
- name: Install useful apps
  hosts: all
  remote_user: root

  tasks:
    - name: Install usefull apps
      apt:
        name:
          [
            "zsh",
            "tig",
            "neovim",
            "wget",
            "curl",
            "exa",
            "trash-cli",
            "tmux",
            "git",
            "tig",
            "wget",
            "neofetch",
            "htop",
            "fzy",
          ]
        update_cache: yes
        state: latest
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
